### ISSUE TITLE
Requirement for stable, long-term service availability

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/stc#19]
During discussion at the [GeoSemantics Symposium](https://esipfed.github.io/stc/symposium.html) @skybristol and @lewismc raised the topic of long-term (~3 years) availability of a stable semantic repository implementation such that it can be reliably and confidently used in ongoing and future Testbed projects. The concept of a SRI becomes very appealing only if there is a guarantee that it will be around for a while and that it will be maintained. Reasoning behind the above is simple, we are very keen to build off of, delegate to, and leverage an SRI... we therefore need to be confident that the resource will be available for longer term use.

**Comment by skybristol** [comment]
One of the working notions that we are pursuing as part of a USGS-funded ESIP Testbed project is that we, as US Government "long-term data agencies," need and can benefit from contributing to a suite of community-based operational technology resources in addition to the core assets that we manage within our own infrastructure. In our case, we are pursuing this idea with a community-based provenance repository and service for W3C-PROV information. Currently, ESIP provides administrative (mainly fiscal) support for a small handful of technologies operating on cloud resources. Our group has been working up methodology for robust resource deployment using Kubernetes and other state of the art DevOps tech for our own USGS-"owned" cloud as well the ESIP-facilitated cloud, exploring the various operational dynamics and constraints we have to deal with. This is giving us a sense for what it would take, long term, for us to contribute to a community-based suite of technical capabilities that we have vested interest in but would like to contribute to and share with other members of our earth system science family.

However, this is not really a technical problem; it is a cultural and governance problem. Beyond helping to get all of us across the government, academic, commercial, and NGO institiutions together regularly as a community of practice to work on problems, could ESIP also help serve as a "digital Switzerland," helping to provide a community-owned platform for operational data capabilities? How would it be governed and managed? How would it be funded over the long term? What are the appropriate resources to run on ESIP, and how do we make those decisions? If we are to pursue this whole idea, how do we set up a controlled experiment to test a notional concept of operations?

**Comment by rduerr** [comment]
The only way I can imagine it working is for the "digital Switzerland" to be funded by all the various members (agencies, commercial institutions, etc.) that use it.  The issue there is how do organizations like the Ronin Insitute which is entirely virtual, has practically no overhead, etc. participate?  I participate but as an individual even though I am the Ronin representative.

**Comment by graybeal** [comment]
I am not sure the goal in raising of this issue. 

In the larger context, the reason the ongoing evaluation of semantic repositories has been undertaken by ESIP -- and part of the reason that ESIP changed the Semantic working group to a committee, I'm guessing -- was so that it (ESIP) could evaluate the cost and effectiveness of alternate approaches to addressing this problem—not just for testbed projects, but also for the entire earth science community. Many in the ESIP community believed that ESIP was uniquely positioned to take on this responsibility, and have been advocating for that, for the reasons described in this thread. 

In the end, it is the ESIP organization as a whole, led by the board of directors (?) and informed by the Semantic Committee and the ongoing evaluation, that has to make that decision. 

Many of the previous discussions of the STC and its forerunner working group was to socialize the cultural and governance problem that Sky describes. The way this problem is being socialized is through extensive exposure of the ESIP community, and particularly its semantic community, to existing solutions and their associated challenges. (The simultaneous adoption of SWEET also adds considerably to this insight, though I believe it is an orthogonal aspect of ESIP's semantic approach.)

Finally, I don't think "The concept of a SRI becomes very appealing only if there is a guarantee that it will be around for a while and that it will be maintained." adequately states the requirement. I believe the commitment has to be to a quasi-permanent service, meaning essentially decades and beyond. 

As a related personal observation, when we started MMI ORR over 12 years ago, this was the commitment that I made to myself and to the marine community, that MMI ORR would be there indefinitely for this purpose.  While I can't swear that anyone besides myself took that guarantee seriously, I think you can see that at least for the first of those many decades, we've fulfilled the commitment. I'm happy to make another 3-year commitment, and am young enough to make the next 10-year commitment, but we'll all be happier when we have someone—like ESIP—taking responsibility for ensuring a more long-term presence.

So the action you seek, building toward a long-term institutional commitment, is being undertaken at an organizational level, not just for Testbeds but well beyond that.

**Comment by lewismc** [comment]
Hi folks, with @abburgess 's announcement at last weeks SemTech meeting it looks like COR is going to be supported moving forward. I'm going to close this issue off, thank you for everyone that participated in the conversation and I am glad to see that we are moving on.
